name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Quarto
        run: |
          curl -L https://quarto.org/install | sh
          quarto install

      - name: Render website
        run: quarto render

      - name: Deploy to GitHub Pages
        uses: actions/upload-artifact@v2
        with:
          name: website
          path: public

      - name: Deploy to GitHub Pages
        uses: actions/deploy-to-github-pages@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repository: devendrarajm/devendrarajm.github.io
          target_branch: main
